import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Dash Board',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="zh-cn">
      <body className="w-screen h-screen ">{children}</body>
    </html>
  )
}
