import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Dash Board',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="zh-cn" className="w-full h-full">
      <body className="w-full h-full ">
        {children}
      </body>
    </html>
  )
}
